build-n-run-1:
	ghc -o Day18_1.out -threaded -main-is Day18 Day18.hs && time ./Day18_1.out +RTS -N6

build-n-run-2:
	ghc -o Day18_2.out -threaded -main-is Day18 Day18.hs && time ./Day18_2.out +RTS -N6